version: "3"

services:
  app:
    build: .
    container_name: ruby-timesheets-test-local
    working_dir: /usr/src/ruby-timesheets
    environment:
      - GITLAB_API_PRIVATE_TOKEN
      - GITLAB_API_ENDPOINT
      - GITLAB_GROUP
      - OUTFILE
      - FIELD_DELIMITER
      - MG_API_KEY
      - MG_DOMAIN
      - FROM_ADDRESS
      - TO_ADDRESS
